package com.ia.project.dynamicstudyplanner.api.dto;
import com.ia.project.dynamicstudyplanner.domain.FitnessBreakdown;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Data Transfer Object for an OptimizationResult.
 * Contains the detailed results of the genetic algorithm's execution.
 *
 * @param plan The optimized study plan.
 * @param fitness The final fitness score of the best plan found.
 * @param generationsRun The total number of generations the algorithm ran for.
 * @param executionTimeMillis The total time in milliseconds the optimization process took.
 */
@Schema(description = "The strategic result generated by the Genetic Algorithm.")
public record OptimizationResultDto(
        @Schema(description = "The allocated study days for each subject.")
        StudyPlanDto plan,
        @Schema(description = "The final calculated fitness score of the best individual.", example = "142.55")
        double fitness,
        @Schema(description = "The number of evolutionary generations processed before finding this solution.",
                example = "100")
        int generationsRun,
        @Schema(description = "The total execution time of the optimization algorithm in milliseconds.", example = "45")
        long executionTimeMillis,
        @Schema(description = "Version of the build that produced this plan. Together with the "
                + "request payload and its randomSeed, it is what makes a run replayable.",
                example = "2.0.1")
        String coreVersion,
        @Schema(description = "The same fitness, decomposed into the terms that produced it: each "
                + "term's normalised value, its declared weight and what it contributed. The "
                + "aggregate is exactly the fitness field above.")
        FitnessBreakdown fitnessBreakdown
) {}
