package com.ia.project.dynamicstudyplanner.api.dto;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Data Transfer Object for an OptimizationResult.
 * Contains the detailed results of the genetic algorithm's execution.
 *
 * @param plan The optimized study plan.
 * @param fitness The final fitness score of the best plan found.
 * @param generationsRun The total number of generations the algorithm ran for.
 * @param executionTimeMillis The total time in milliseconds the optimization process took.
 */
@Schema(description = "The strategic result generated by the Genetic Algorithm.")
public record OptimizationResultDto(
        @Schema(description = "The allocated study days for each subject.")
        StudyPlanDto plan,
        @Schema(description = "The final calculated fitness score of the best individual.", example = "142.55")
        double fitness,
        @Schema(description = "The number of evolutionary generations processed before finding this solution.",
                example = "100")
        int generationsRun,
        @Schema(description = "The total execution time of the optimization algorithm in milliseconds.", example = "45")
        long executionTimeMillis
) {}
